[Tests] tree-sitter and related version updates
Update to tree-sitter 0.21.3 and tree-sitter-languages 1.10.2.

This is for wheels for Python 3.12, but also that distutils was removed
from Python 3.12 and was seeing this error

________________ ERROR collecting tests/generators/test_cpp.py _________________
ImportError while importing test module '/Users/runner/work/OpenAssetIO-TraitGen/OpenAssetIO-TraitGen/tests/generators/test_cpp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests/generators/test_cpp.py:33: in <module>
    from tree_sitter_languages import get_parser, get_language
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tree_sitter_languages/__init__.py:4: in <module>
    from .core import get_language, get_parser
tree_sitter_languages/core.pyx:4: in init tree_sitter_languages.core
    ???
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tree_sitter/__init__.py:4: in <module>
    from distutils.ccompiler import new_compiler
E   ModuleNotFoundError: No module named 'distutils'

Note there are no wheels for newer Python versions at this time.

The tree-sitter version is not the latest, as I found that going to the
latest caused incompatibilities with tree-sitter-language.

Also, there were some required fixes to the predicates, which omitted
the required # prefix as described in the documentation

https://tree-sitter.github.io/tree-sitter/using-parsers/queries/3-predicates-and-directives.html

Errors were of the form

NameError: Invalid node type eq?

Note that Copilot helped discover the issues in the tests. The theory
was that the older tree-sitter version tolerated the missing prefix.

Part of #136

Signed-off-by: Mark Final <mark.final@foundry.com>